// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/cart/cart.proto

package cart

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CartInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SizeId        int64                  `protobuf:"varint,4,opt,name=size_id,json=sizeId,proto3" json:"size_id,omitempty"`
	Num           int64                  `protobuf:"varint,5,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartInfo) Reset() {
	*x = CartInfo{}
	mi := &file_proto_cart_cart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartInfo) ProtoMessage() {}

func (x *CartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartInfo.ProtoReflect.Descriptor instead.
func (*CartInfo) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{0}
}

func (x *CartInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CartInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CartInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartInfo) GetSizeId() int64 {
	if x != nil {
		return x.SizeId
	}
	return 0
}

func (x *CartInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ResponseAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartId        int64                  `protobuf:"varint,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseAdd) Reset() {
	*x = ResponseAdd{}
	mi := &file_proto_cart_cart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAdd) ProtoMessage() {}

func (x *ResponseAdd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAdd.ProtoReflect.Descriptor instead.
func (*ResponseAdd) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseAdd) GetCartId() int64 {
	if x != nil {
		return x.CartId
	}
	return 0
}

func (x *ResponseAdd) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Clean struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Clean) Reset() {
	*x = Clean{}
	mi := &file_proto_cart_cart_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Clean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Clean) ProtoMessage() {}

func (x *Clean) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Clean.ProtoReflect.Descriptor instead.
func (*Clean) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{2}
}

func (x *Clean) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meg           string                 `protobuf:"bytes,1,opt,name=meg,proto3" json:"meg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_cart_cart_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetMeg() string {
	if x != nil {
		return x.Meg
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChangeNum     int64                  `protobuf:"varint,2,opt,name=change_num,json=changeNum,proto3" json:"change_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_cart_cart_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetChangeNum() int64 {
	if x != nil {
		return x.ChangeNum
	}
	return 0
}

type CartID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartID) Reset() {
	*x = CartID{}
	mi := &file_proto_cart_cart_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartID) ProtoMessage() {}

func (x *CartID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartID.ProtoReflect.Descriptor instead.
func (*CartID) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{5}
}

func (x *CartID) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CartFindAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartFindAll) Reset() {
	*x = CartFindAll{}
	mi := &file_proto_cart_cart_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartFindAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartFindAll) ProtoMessage() {}

func (x *CartFindAll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartFindAll.ProtoReflect.Descriptor instead.
func (*CartFindAll) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{6}
}

func (x *CartFindAll) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CartAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CartInfo      []*CartInfo            `protobuf:"bytes,1,rep,name=cart_info,json=cartInfo,proto3" json:"cart_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartAll) Reset() {
	*x = CartAll{}
	mi := &file_proto_cart_cart_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartAll) ProtoMessage() {}

func (x *CartAll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cart_cart_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartAll.ProtoReflect.Descriptor instead.
func (*CartAll) Descriptor() ([]byte, []int) {
	return file_proto_cart_cart_proto_rawDescGZIP(), []int{7}
}

func (x *CartAll) GetCartInfo() []*CartInfo {
	if x != nil {
		return x.CartInfo
	}
	return nil
}

var File_proto_cart_cart_proto protoreflect.FileDescriptor

const file_proto_cart_cart_proto_rawDesc = "" +
	"\n" +
	"\x15proto/cart/cart.proto\x12\x04cart\"}\n" +
	"\bCartInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x17\n" +
	"\asize_id\x18\x04 \x01(\x03R\x06sizeId\x12\x10\n" +
	"\x03num\x18\x05 \x01(\x03R\x03num\"8\n" +
	"\vResponseAdd\x12\x17\n" +
	"\acart_id\x18\x01 \x01(\x03R\x06cartId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\" \n" +
	"\x05Clean\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03meg\x18\x01 \x01(\tR\x03meg\"5\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"change_num\x18\x02 \x01(\x03R\tchangeNum\"\x18\n" +
	"\x06CartID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"&\n" +
	"\vCartFindAll\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"6\n" +
	"\aCartAll\x12+\n" +
	"\tcart_info\x18\x01 \x03(\v2\x0e.cart.CartInfoR\bcartInfo2\x8e\x02\n" +
	"\x04Cart\x12.\n" +
	"\aAddCart\x12\x0e.cart.CartInfo\x1a\x11.cart.ResponseAdd\"\x00\x12*\n" +
	"\tCleanCart\x12\v.cart.Clean\x1a\x0e.cart.Response\"\x00\x12$\n" +
	"\x04Incr\x12\n" +
	".cart.Item\x1a\x0e.cart.Response\"\x00\x12$\n" +
	"\x04Decr\x12\n" +
	".cart.Item\x1a\x0e.cart.Response\"\x00\x120\n" +
	"\x0eDeleteItemByID\x12\f.cart.CartID\x1a\x0e.cart.Response\"\x00\x12,\n" +
	"\x06GetAll\x12\x11.cart.CartFindAll\x1a\r.cart.CartAll\"\x00B\x0eZ\f./proto;cartb\x06proto3"

var (
	file_proto_cart_cart_proto_rawDescOnce sync.Once
	file_proto_cart_cart_proto_rawDescData []byte
)

func file_proto_cart_cart_proto_rawDescGZIP() []byte {
	file_proto_cart_cart_proto_rawDescOnce.Do(func() {
		file_proto_cart_cart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cart_cart_proto_rawDesc), len(file_proto_cart_cart_proto_rawDesc)))
	})
	return file_proto_cart_cart_proto_rawDescData
}

var file_proto_cart_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_cart_cart_proto_goTypes = []any{
	(*CartInfo)(nil),    // 0: cart.CartInfo
	(*ResponseAdd)(nil), // 1: cart.ResponseAdd
	(*Clean)(nil),       // 2: cart.Clean
	(*Response)(nil),    // 3: cart.Response
	(*Item)(nil),        // 4: cart.Item
	(*CartID)(nil),      // 5: cart.CartID
	(*CartFindAll)(nil), // 6: cart.CartFindAll
	(*CartAll)(nil),     // 7: cart.CartAll
}
var file_proto_cart_cart_proto_depIdxs = []int32{
	0, // 0: cart.CartAll.cart_info:type_name -> cart.CartInfo
	0, // 1: cart.Cart.AddCart:input_type -> cart.CartInfo
	2, // 2: cart.Cart.CleanCart:input_type -> cart.Clean
	4, // 3: cart.Cart.Incr:input_type -> cart.Item
	4, // 4: cart.Cart.Decr:input_type -> cart.Item
	5, // 5: cart.Cart.DeleteItemByID:input_type -> cart.CartID
	6, // 6: cart.Cart.GetAll:input_type -> cart.CartFindAll
	1, // 7: cart.Cart.AddCart:output_type -> cart.ResponseAdd
	3, // 8: cart.Cart.CleanCart:output_type -> cart.Response
	3, // 9: cart.Cart.Incr:output_type -> cart.Response
	3, // 10: cart.Cart.Decr:output_type -> cart.Response
	3, // 11: cart.Cart.DeleteItemByID:output_type -> cart.Response
	7, // 12: cart.Cart.GetAll:output_type -> cart.CartAll
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_cart_cart_proto_init() }
func file_proto_cart_cart_proto_init() {
	if File_proto_cart_cart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cart_cart_proto_rawDesc), len(file_proto_cart_cart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cart_cart_proto_goTypes,
		DependencyIndexes: file_proto_cart_cart_proto_depIdxs,
		MessageInfos:      file_proto_cart_cart_proto_msgTypes,
	}.Build()
	File_proto_cart_cart_proto = out.File
	file_proto_cart_cart_proto_goTypes = nil
	file_proto_cart_cart_proto_depIdxs = nil
}
