global:
  scrape_interval: 15s # 默认抓取间隔
  evaluation_interval: 15s # 规则评估间隔

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cartApi'
    static_configs:
      - targets: ['host.docker.internal:9101']

  - job_name: 'cart'
    static_configs:
      - targets: ['host.docker.internal:9104']
  - job_name: 'order'
    static_configs:
      - targets: ['host.docker.internal:9102']
  - job_name: 'product'
    static_configs:
      - targets: ['host.docker.internal:9103']
#  - job_name: 'consul-services'  # 任务名，自定义
#    # 1. 配置Consul服务发现地址
#    consul_sd_configs:
#      - server: 'host.docker.internal:8500'  # Consul服务端地址（默认端口8500）
#        datacenter: 'dc1'  # Consul数据中心（默认dc1，按需修改）
#        tag_separator: ','
#        scheme: 'http'  # 若Consul启用HTTPS则改为https
#    relabel_configs:
#      - source_labels: [ __meta_consul_service_metadata_prometheus_monitor ]  # 要检查的元标签
#        regex: "true"                                                       # 匹配标签值为 "true"
#        action: keep
      
