global:
  scrape_interval: 15s # 默认抓取间隔
  evaluation_interval: 15s # 规则评估间隔

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cart-api'
    static_configs:
      - targets: ['host.docker.internal:9100']
      
  # 可以在这里添加更多需要监控的目标
  # - job_name: 'your-service'
  #   static_configs:
  #     - targets: ['your-service:port']
