server:
  host: 127.0.0.1
  port: "18888"
  mode: debug
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  service_name: go.micro.service.cartApi
database:
  host: localhost
  port: "3600"
  username: root
  password: "123456"
  database: ecommerce
  ssl_mode: disable
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  host: localhost
  port: "6379"
  password: ""
  database: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

jwt:
  secret: your-jwt-secret-key
  access_expiration: 15m
  refresh_expiration: 24h
  issuer: ecommerce-service

log:
  level: info
  format: json
  output: stdout
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

rabbitmq:
  host: localhost
  port: "5672"
  username: guest
  password: guest
  vhost: "/"

etcd:
  endpoints:
    - localhost:2379
  username: ""
  password: ""
  dial_timeout: 5s
  ttl: 30

jaeger:
  enabled: false
  host: localhost
  port: "4317"
  sample_rate: 0.1
  deployment: dev
  use_tls: false

metrics:
  enabled: true
  host: 0.0.0.0
  port: "9100"
  path: /metrics

security:
  rate_limit_rps: 100
  rate_limit_burst: 200
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - "*"
  expose_headers: []
  allow_credentials: true
